#pragma once

#define FRPC_GUI_VERSION_MAJOR 0
#define FRPC_GUI_VERSION_MINOR 1
#define FRPC_GUI_VERSION_PATCH 0
#define FRPC_GUI_VERSION_BUILD 0
#define FRPC_GUI_VERSION_STRING "0.1.0"
#define FRPC_GUI_VERSION_WSTRING L"0.1.0"

